version: '3.8'

services:

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "50007:50007"
  
  backend:
    build:
      context: backend/
  
  hello_world:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
