version: '3.8'

services:

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "50007:50007"

  hello_world:
    build:
      context: .
      dockerfile: Dockerfile
