version: '3.8'

services:

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "8000:8000"

  hello_world:
    build:
      context: .
      dockerfile: Dockerfile
