name: CI

on:
  push:
    branches: [ main ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build Dockerfile
      run: make docker
    - name: Run Dockerfile
      run: docker run -d hello_world
    - name: Copy coverage files
      run: CONTAINER_ID=$(sudo docker ps -aql) && docker cp $CONTAINER_ID:/tflite-micro/tensorflow#lite#micro#examples#hello_world#hello_world_test.cc.gcov .
    - name: Upload coverage...
      uses: codecov/codecov-action@v3
      with:
        verbose: true
        gcov: true
        #gcov_include: tensorflow#lite#micro#examples#hello_world#hello_world_test.cc.gcov
