name: CI

on:
  pull-request:
    branches: [ main ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build and Run Dockerfile
      run: make docker
